wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1709721262
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.14
      8:
      - 5
arch:
  desc: null
  value: resnet50
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
